scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:white_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:orange_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:magenta_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:light_blue_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:yellow_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:lime_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:pink_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:gray_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:light_gray_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:cyan_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:purple_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:blue_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:brown_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:green_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:red_shulker_box"}}
scoreboard players tag @e[type=Item,tag=!isNotEmpty] add isEmpty {Item:{id:"minecraft:black_shulker_box"}}